from php:7.3-apache

RUN docker-php-ext-install pdo_mysql \
 && docker-php-ext-enable pdo_mysql

RUN curl -LsS https://codeception.com/codecept.phar -o /usr/local/bin/codecept
RUN chmod a+x /usr/local/bin/codecept

WORKDIR /var/www/test
